blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/maiko/llm-chatbot-kit/security/policy
    about: Please report security vulnerabilities via GitHub security policy.
