name: Build Docs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material

      - name: Build site
        run: mkdocs build --strict

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/
