name: Lint and Test

on:
  pull_request:
    branches: ["**"]
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches: ["main"]
    tags: ["v*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python (3.11)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      - name: Lint (ruff)
        run: ruff check src
      - name: Format check (black)
        run: black --check src/llm_chatbot tests

  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install package and pytest
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
      - name: Run tests
        env:
          PYTHONWARNINGS: default
        run: pytest -q

  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    needs: [lint, tests]
    steps:
      - name: Aggregate
        run: echo "Lint and Test checks passed."
